import type { Metadata } from "next";
import "./globals.css";


export const metadata: Metadata = {
  title: "Shop",
  description: "Generated by create my-shop",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="body__layout">
        {children}
      </body>
    </html>
  );
}
